server:
  ip    : '127.0.0.1'
  port  : '12345'

forecast:
  site           : ''
  api            : ''
  city_name      : ''
  country_code   : ''

rooms:
  mac1 : 'bedroom_1'
  mac2 : 'bedroom_2'
  mac3 : 'living_room'
  mac4 : 'kitchen'

mode:
  kt  :  18
  scheduler: 

    default: 18
